# Generated by Django 3.2 on 2023-04-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cat',
            table='cats',
        ),
    ]
